### ISSUE TITLE
Will there ever be a Light weight?

### ISSUE THREAD

**Issue by nadropper** [mass-driver/md-io#12]
Hi, a big fan of MD IO here. I just want to know whether you'll ever consider adding a Light weight to the family.

**Comment by rutherfordcraze** [comment]
Hey, I have great news on that front! The next update, v0.7, will introduce new Thin and Light styles later this week. (The Thin Italic & Light Italic styles will be added in v0.8, since they need a little more work — that’s hopefully only a couple months away.)

<img width="1122" alt="MD IO v0.7 style overview. There are eight roman and six italic styles, with the two lightest weights only available in the roman fonts." src="https://github.com/mass-driver/md-io/assets/17358105/cbe43666-a3d1-45b7-ba57-6c0b0591e44d">

**Comment by nadropper** [comment]
That's awesome. Thanks!
