### ISSUE TITLE
Versioning font names

### ISSUE THREAD

**Issue by JoshApos** [mass-driver/md-io#3]
This is admittedly minor, but figured I'd raise it in case there's a relatively easy alternative. Having the version number as part of the font name (e.g. MD IO **0.1**) will require users to update the settings in their various text editors / CLIs of choice every time a new update is released, adding friction.

**Comment by rutherfordcraze** [comment]
Hey! This is an interesting point to raise. With other releases, I’ve included the version number in the font name, for a couple of reasons:
- Changing metrics/spacing/kerning values between versions can break some designs; it’s sometimes necessary to have multiple versions installed at once in order to update things like this manually.
- Clearing the font cache (on macOS at least) is kinda tricky, not every user knows how to do it (or even that they’d need to). I’m not totally clear on how to include that step in the update process.

I do think the current setup is flawed though — changing the font in an IDE/CLI/etc is usually more involved than with graphic design software. It might be possible to include two versions in the release files (one with a version number and one without) then let people choose which method they prefer, although that could be tricky to communicate.

In any case, thanks for opening this issue. I’ll have a think about other solutions — if it’s possible to remove that friction, it’s worth doing.

**Comment by JoshApos** [comment]
Ah yeah, these are fair considerations. Thanks for taking the time to walk through the thought process either way!
