### ISSUE TITLE
Operator alignment

### ISSUE THREAD

**Issue by motform** [mass-driver/md-io#8]
Hi,

First off, fantastic typeface! Really looking forward to see how this develops. 

I would like to adress the fascinating issue of operator alignment. Right now, a lot of operators are aligned slightly above x-height, leading to discomfort in programming situations where operators occur next to lower case glyphs. This is very noticeable  Lisps where it is common to use glyphs like ´*´ or ´+´ to make "earmuffs" and where ´-´ are used as word spacing. 

Compare MD IO:

<img width="468" alt="Screenshot 2021-03-23 at 18 57 06" src="https://user-images.githubusercontent.com/30436214/112195591-6eb74c00-8c0a-11eb-8b89-c6685d35473b.png">

to Pragmata Pro:

<img width="443" alt="Screenshot 2021-03-23 at 18 57 21" src="https://user-images.githubusercontent.com/30436214/112195672-855da300-8c0a-11eb-88bd-39f96d48b658.png">

MD IO arguably handles `op` `uppercase` better, but I would argue that `op` `lowercase` is more common in code and a sensible default in environment that might not handle upper open type `case` features are not available (looking at you, Emacs).

**Comment by motform** [comment]
This also affect common glyph combinations like arrows, `->` where the visual centre looks off. (The `>` could also be a bit more open to invite to arrows, but that is personal preference)

**Comment by rutherfordcraze** [comment]
Hey, this is a really great point — sorry it’s taken so long to write up a response!

With the versions up until now, I think I’ve applied a more conventional logic to the operators, which is to assume they’ll be mostly used adjacent to numbers and make sure that usage looks best. But you’re right, in code that’s not a helpful assumption — aligning them to the lowercase (or slightly higher) makes more sense. I’ve done that for the upcoming v0.3

I‘ve also opened up `<` & `>` just a little. Regular & italic:

<img width="778" alt="MD IO 0.3" src="https://user-images.githubusercontent.com/17358105/132953512-e1383d22-bc3a-47aa-89a0-f88c2054fbdf.png">

I maybe still have some issue with extending the ‘operator’ designation to include `*`, since the new alignment makes that generally more awkward as a footnote indicator. For now I’m still aligning it with the lowercase and `+=>` (etc.), but I’ll keep thinking about how exactly I want to handle that.

Thanks for opening the issue, it’s been really useful to think about. I’m aiming to have v0.3 out on the 20th, so you can see these changes first-hand :)

**Comment by motform** [comment]
I think this look great, well done! That looks much more neutral in all regards. I did not consider the footnote use case, but I think your reasoning makes sense, especially considering the popularity of monospace typefaces in writing software. 

PS: The italic looks fantastic, can't wait to try 0.3 out!

**Comment by rutherfordcraze** [comment]
I’ve taken another look at this ahead of the v0.5 update, and on reflection I’m happy with the current setup — `*` aligned to the lowercase seems to be where people want it, so unless I decide to add a contextual alignment for footnotes, it can stay where it is.
